name: sunil_oidc
on: workflow_dispatch
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Troubleshooting
          run: |
              curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
              jq "{ jwt: .value, role: \"$VAULT_ROLE\" }" > ./token.json

              echo 'GitHub Actions Token Claims'
              cat ./token.json | jq -r '.jwt | split(".") | .[1] | @base64d' | jq
              echo 'Vault Login Response'
              curl -sSLf -X POST -H "Content-Type: application/json" -H "X-Vault-Namespace: admin" --data @token.json $VAULT_URL/v1/auth/$VAULT_AUTH_PATH/login
              # Remove the token file when we're done (if we don't fail)
              rm ./token.json
          env:
            VAULT_URL: http://18.217.212.16:8200
            VAULT_AUTH_PATH: jwt
            VAULT_ROLE: sunil-oidc-role
        - name: Get Secrets from valuts
          id: secretdata
          uses: hashicorp/vault-action@v2.4.0
          with:
              url: http://18.217.212.16:8200
              tlsSkipVerify: true
              role: sunil-oidc-role 
              method: jwt
              namespace: admin
              secrets: |
                secret/data/ci app_secret
        - name: Print Secrets
          run: |
            echo ${{ env.APP_SECRET }} | sed 's/./& /g'; python simple.py
        #- name: Run tmate
        #  uses: mxschmitt/action-tmate@v2
        - name: run python script
          shell: bash
          run: |
            python simple.py 
