name: sunil_oidc

on: push
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
        - name: Get Secrets from valut
          uses: hashicorp/vault-action@v2.4.0
          with:
              url: http://18.217.212.16:8200
              tlsSkipVerify: true
              role: sunil-oidc-role
              method: jwt
              secrets: |
                    secret/data/ci app_secret
